/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as subscriptionSol from "./subscription.sol";
export type { subscriptionSol };
export type { ERC20Mock } from "./ERC20Mock";
