# Generated by Django 4.2.14 on 2025-09-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
